# Significant update to windows_utils.bzl from bazel-lib
# Now contains v3 runfiles logic
# Would like to contribute this back to bazel-lib

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "windows_utils",
    srcs = ["windows_utils.bzl"],
    visibility = ["//:__pkg__"],
)
